# Generated by Django 3.1.4 on 2021-01-04 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20210104_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='purchase_date',
        ),
    ]
