# Generated by Django 3.1.4 on 2021-01-04 08:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_product_purchase_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='purchase_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
