# Generated by Django 3.1.4 on 2021-01-04 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210102_1417'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='city',
            new_name='state',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='gender',
        ),
    ]
